version: "3.9"

services:
  php:
    build:
      context: ./docker/php-fpm
      dockerfile: .Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_MODE: "debug,develop"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    user: "1000:1000"
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: .Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  composer:
    image: composer:2.1
    volumes:
      - ./:/app
    working_dir: /app
    command: ["sh", "-c", "composer install --ignore-platform-reqs && composer dump-autoload"]
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: